spring:
  activemq:
#    broker-url: tcp://39.107.159.236:61616
    broker-url: tcp://localhost:61616
    username: user
    password: user
    in-memory: false  #true 表示使用内置的MQ，false则连接服务器
    pool:
      enabled: true  #true表示使用连接池；false时，每发送一条数据创建一个连接
      max-connections: 10  #连接池最大连接数
      idle-timeout: 30000    #空闲的连接过期时间，默认为30秒
